version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - no_net
      - no_json
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
gomod:
  proxy: true
  mod: mod
archives:
  - format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
dockers:
  - image_templates: ["ghcr.io/grol-io/{{ .ProjectName }}:{{ .Version }}-amd64"]
    use: buildx
    goarch: amd64
    build_flag_templates:
    - --platform=linux/amd64
  - image_templates: ["ghcr.io/grol-io/{{ .ProjectName }}:{{ .Version }}-arm64"]
    use: buildx
    goarch: arm64
    build_flag_templates:
    - --platform=linux/arm64
docker_manifests:
-
  name_template: ghcr.io/grol-io/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - grol/{{ .ProjectName }}:{{ .Version }}-amd64
  - grol/{{ .ProjectName }}:{{ .Version }}-arm64
-
  name_template: ghcr.io/grol-io/{{ .ProjectName }}:latest
  image_templates:
  - grol/{{ .ProjectName }}:{{ .Version }}-amd64
  - grol/{{ .ProjectName }}:{{ .Version }}-arm64
release:
  prerelease: auto
  mode: append
# .goreleaser.yaml
brews:
  -
    # GitHub/GitLab repository to push the formula to
    repository:
      owner: grol-io
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    directory: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://grol.io/"

    # Template of your app's description.
    # Default is empty.
    description: "{{ .Env.TAP_DESCRIPTION }}"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      assert_match version.to_s, shell_output("#{bin}/{{ .ProjectName }} -version")
