
s :=0
// check that := works too in for loop.
for n := 4 {
	s = s+ n
}
// 0 + 1 + 2 + 3 = 6
if s != 6 {
	error("Expected 6, got", s) // was 16 before the fix.
}

// for of array/global (#328)

arr := [1,2,3]
res := 0
for i := arr {
	res = res +i
}
Assert("for of array/global", res == 6)

// same inside a function

func testRef() {
	res := 0
	for i := arr {
		res = res + i
	}
	return res
}

NoErr("for global array inside a function", testRef(), "6")
