// Code generated by "stringer -type=Type"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[INTEGER-1]
	_ = x[BOOLEAN-2]
	_ = x[NIL-3]
	_ = x[ERROR-4]
	_ = x[RETURN-5]
	_ = x[FUNCTION-6]
	_ = x[STRING-7]
	_ = x[ARRAY-8]
	_ = x[MAP-9]
	_ = x[QUOTE-10]
	_ = x[LAST-11]
}

const _Type_name = "UNKNOWNINTEGERBOOLEANNILERRORRETURNFUNCTIONSTRINGARRAYMAPQUOTELAST"

var _Type_index = [...]uint8{0, 7, 14, 21, 24, 29, 35, 43, 49, 54, 57, 62, 66}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
