// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOL-1]
	_ = x[startValueTokens-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[LINECOMMENT-7]
	_ = x[BLOCKCOMMENT-8]
	_ = x[REGISTER-9]
	_ = x[endValueTokens-10]
	_ = x[startSingleCharTokens-11]
	_ = x[ASSIGN-12]
	_ = x[PLUS-13]
	_ = x[MINUS-14]
	_ = x[BANG-15]
	_ = x[ASTERISK-16]
	_ = x[SLASH-17]
	_ = x[PERCENT-18]
	_ = x[LT-19]
	_ = x[GT-20]
	_ = x[BITAND-21]
	_ = x[BITOR-22]
	_ = x[BITXOR-23]
	_ = x[BITNOT-24]
	_ = x[COMMA-25]
	_ = x[SEMICOLON-26]
	_ = x[LPAREN-27]
	_ = x[RPAREN-28]
	_ = x[LBRACE-29]
	_ = x[RBRACE-30]
	_ = x[LBRACKET-31]
	_ = x[RBRACKET-32]
	_ = x[COLON-33]
	_ = x[DOT-34]
	_ = x[endSingleCharTokens-35]
	_ = x[startMultiCharTokens-36]
	_ = x[LTEQ-37]
	_ = x[GTEQ-38]
	_ = x[EQ-39]
	_ = x[NOTEQ-40]
	_ = x[INCR-41]
	_ = x[DECR-42]
	_ = x[DOTDOT-43]
	_ = x[OR-44]
	_ = x[AND-45]
	_ = x[LEFTSHIFT-46]
	_ = x[RIGHTSHIFT-47]
	_ = x[LAMBDA-48]
	_ = x[DEFINE-49]
	_ = x[endMultiCharTokens-50]
	_ = x[startIdentityTokens-51]
	_ = x[FUNC-52]
	_ = x[TRUE-53]
	_ = x[FALSE-54]
	_ = x[IF-55]
	_ = x[ELSE-56]
	_ = x[RETURN-57]
	_ = x[FOR-58]
	_ = x[BREAK-59]
	_ = x[CONTINUE-60]
	_ = x[MACRO-61]
	_ = x[QUOTE-62]
	_ = x[UNQUOTE-63]
	_ = x[LEN-64]
	_ = x[FIRST-65]
	_ = x[REST-66]
	_ = x[PRINT-67]
	_ = x[PRINTLN-68]
	_ = x[LOG-69]
	_ = x[ERROR-70]
	_ = x[CATCH-71]
	_ = x[DEL-72]
	_ = x[endIdentityTokens-73]
	_ = x[EOF-74]
}

const _Type_name = "ILLEGALEOLstartValueTokensIDENTINTFLOATSTRINGLINECOMMENTBLOCKCOMMENTREGISTERendValueTokensstartSingleCharTokensASSIGNPLUSMINUSBANGASTERISKSLASHPERCENTLTGTBITANDBITORBITXORBITNOTCOMMASEMICOLONLPARENRPARENLBRACERBRACELBRACKETRBRACKETCOLONDOTendSingleCharTokensstartMultiCharTokensLTEQGTEQEQNOTEQINCRDECRDOTDOTORANDLEFTSHIFTRIGHTSHIFTLAMBDADEFINEendMultiCharTokensstartIdentityTokensFUNCTRUEFALSEIFELSERETURNFORBREAKCONTINUEMACROQUOTEUNQUOTELENFIRSTRESTPRINTPRINTLNLOGERRORCATCHDELendIdentityTokensEOF"

var _Type_index = [...]uint16{0, 7, 10, 26, 31, 34, 39, 45, 56, 68, 76, 90, 111, 117, 121, 126, 130, 138, 143, 150, 152, 154, 160, 165, 171, 177, 182, 191, 197, 203, 209, 215, 223, 231, 236, 239, 258, 278, 282, 286, 288, 293, 297, 301, 307, 309, 312, 321, 331, 337, 343, 361, 380, 384, 388, 393, 395, 399, 405, 408, 413, 421, 426, 431, 438, 441, 446, 450, 455, 462, 465, 470, 475, 478, 495, 498}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
