// Code generated by "stringer -type=Priority"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LOWEST-1]
	_ = x[ASSIGN-2]
	_ = x[OR-3]
	_ = x[AND-4]
	_ = x[EQUALS-5]
	_ = x[LESSGREATER-6]
	_ = x[SUM-7]
	_ = x[PRODUCT-8]
	_ = x[PREFIX-9]
	_ = x[CALL-10]
	_ = x[INDEX-11]
	_ = x[DOTINDEX-12]
}

const _Priority_name = "LOWESTASSIGNORANDEQUALSLESSGREATERSUMPRODUCTPREFIXCALLINDEXDOTINDEX"

var _Priority_index = [...]uint8{0, 6, 12, 14, 17, 23, 34, 37, 44, 50, 54, 59, 67}

func (i Priority) String() string {
	i -= 1
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return "Priority(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
