// Code generated by "stringer -type=Priority"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LOWEST-1]
	_ = x[ASSIGN-2]
	_ = x[OR-3]
	_ = x[AND-4]
	_ = x[LAMBDA-5]
	_ = x[EQUALS-6]
	_ = x[LESSGREATER-7]
	_ = x[SUM-8]
	_ = x[PRODUCT-9]
	_ = x[PREFIX-10]
	_ = x[CALL-11]
	_ = x[INDEX-12]
	_ = x[DOTINDEX-13]
}

const _Priority_name = "LOWESTASSIGNORANDLAMBDAEQUALSLESSGREATERSUMPRODUCTPREFIXCALLINDEXDOTINDEX"

var _Priority_index = [...]uint8{0, 6, 12, 14, 17, 23, 29, 40, 43, 50, 56, 60, 65, 73}

func (i Priority) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Priority_index)-1 {
		return "Priority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Priority_name[_Priority_index[idx]:_Priority_index[idx+1]]
}
