// Demonstrate internal state update in a lambda.

func decrIter(n) {
	state := n
	() => state--
}

prev = decrIter(3)
println(prev())  // prints 3
println(prev())  // prints 2
println(prev())	 // prints 1
if prev() != 0 {
	error("prev should be 0")
}


func incrIter(n) { // can use n directly as state though maybe not as clear
	() => ++n
}

next = incrIter(5)
println(next())  // prints 6
println(next())  // prints 7
println(next())	 // prints 8
if next() != 9 {
	error("next should be 9")
}
