// Code generated by "stringer -type=Priority"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LOWEST-1]
	_ = x[ASSIGN-2]
	_ = x[EQUALS-3]
	_ = x[LESSGREATER-4]
	_ = x[SUM-5]
	_ = x[PRODUCT-6]
	_ = x[PREFIX-7]
	_ = x[CALL-8]
}

const _Priority_name = "LOWESTASSIGNEQUALSLESSGREATERSUMPRODUCTPREFIXCALL"

var _Priority_index = [...]uint8{0, 6, 12, 18, 29, 32, 39, 45, 49}

func (i Priority) String() string {
	i -= 1
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return "Priority(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
